<?php

use CRM_Yhvrequestform_ExtensionUtil as E;

/**
 * Form controller class
 *
 * @see https://docs.civicrm.org/dev/en/latest/framework/quickform/
 */
class CRM_Yhvrequestform_Form_VolunteerTimetableEdit extends CRM_Core_Form {
  public $_cid;

  public function preProcess() {
    $this->_cid = CRM_Utils_Request::retrieve('cid', 'Positive', $this);
    parent::preProcess(); // TODO: Change the autogenerated stub
  }

  public function buildQuickForm() {
    // add form elements
    CRM_Yhvrequestform_Utils::renderGridElements($this, TRUE);

    $params = [
      'entity_id' => $this->_cid,
      'entity_table' => 'civicrm_contact',
    ];
    $timeTable = CRM_Yhvrequestform_BAO_VolunteerTimetable::getTimeTable($params);
    if (!empty($timeTable)) {
      foreach ($timeTable as $elements) {
        if (!empty($elements['day']) && !empty($elements['time'])) {
          $timeTableDefaults[$elements['day'] . '_' . $elements['time']] = 1;
        }
      }
      $this->setDefaults($timeTableDefaults);
    }
    $this->addButtons(array(
      array(
        'type' => 'submit',
        'name' => E::ts('Save'),
        'isDefault' => TRUE,
      ),
      array(
        'type' => 'cancel',
        'name' => E::ts('Cancel'),
      ),
    ));

    // export form elements
    $this->assign('elementNames', $this->getRenderableElementNames());
    parent::buildQuickForm();
  }

  public function postProcess() {
    $values = $this->exportValues();
    CRM_Yhvrequestform_BAO_VolunteerTimetable::add($this->_cid, $values, TRUE, 'civicrm_contact');
    $this->ajaxResponse['updateTabs']['#tab_volunteer-timetable'] = 1;
    CRM_Core_Session::setStatus(E::ts('Volunteer Availability updated successfully!'), E::ts('Done'), 'success');
    parent::postProcess();
  }

  /**
   * Get the fields/elements defined in this form.
   *
   * @return array (string)
   */
  public function getRenderableElementNames() {
    // The _elements list includes some items which should not be
    // auto-rendered in the loop -- such as "qfKey" and "buttons".  These
    // items don't have labels.  We'll identify renderable by filtering on
    // the 'label'.
    $elementNames = array();
    foreach ($this->_elements as $element) {
      /** @var HTML_QuickForm_Element $element */
      $label = $element->getLabel();
      if (!empty($label)) {
        $elementNames[] = $element->getName();
      }
    }
    return $elementNames;
  }

}
