<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /Users/edsel/Sites/dev/sites/default/files/civicrm/ext/biz.jmaconsulting.yhvrequestform/xml/schema/CRM/Yhvrequestform/VolunteerTimetable.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:e91f31febcfd7572d3788a5880a38081)
 */

/**
 * Database access object for the VolunteerTimetable entity.
 */
class CRM_Yhvrequestform_DAO_VolunteerTimetable extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_volunteer_timetable';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique VolunteerTimetable ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Activity
   *
   * @var int
   */
  public $activity_id;

  /**
   * Number that denotes day of the week
   *
   * @var int
   */
  public $day;

  /**
   * Number that denotes time period
   *
   * @var int
   */
  public $time;

  /**
   * Number of volunteers needed
   *
   * @var int
   */
  public $number_of_volunteers;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_volunteer_timetable';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'activity_id', 'civicrm_activity', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Yhvrequestform_ExtensionUtil::ts('Unique VolunteerTimetable ID'),
          'required' => TRUE,
          'where' => 'civicrm_volunteer_timetable.id',
          'table_name' => 'civicrm_volunteer_timetable',
          'entity' => 'VolunteerTimetable',
          'bao' => 'CRM_Yhvrequestform_DAO_VolunteerTimetable',
          'localizable' => 0,
        ],
        'activity_id' => [
          'name' => 'activity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Yhvrequestform_ExtensionUtil::ts('FK to Activity'),
          'where' => 'civicrm_volunteer_timetable.activity_id',
          'table_name' => 'civicrm_volunteer_timetable',
          'entity' => 'VolunteerTimetable',
          'bao' => 'CRM_Yhvrequestform_DAO_VolunteerTimetable',
          'localizable' => 0,
          'FKClassName' => 'CRM_Activity_DAO_Activity',
        ],
        'day' => [
          'name' => 'day',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Yhvrequestform_ExtensionUtil::ts('Day'),
          'description' => CRM_Yhvrequestform_ExtensionUtil::ts('Number that denotes day of the week'),
          'where' => 'civicrm_volunteer_timetable.day',
          'table_name' => 'civicrm_volunteer_timetable',
          'entity' => 'VolunteerTimetable',
          'bao' => 'CRM_Yhvrequestform_DAO_VolunteerTimetable',
          'localizable' => 0,
        ],
        'time' => [
          'name' => 'time',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Yhvrequestform_ExtensionUtil::ts('Time'),
          'description' => CRM_Yhvrequestform_ExtensionUtil::ts('Number that denotes time period'),
          'where' => 'civicrm_volunteer_timetable.time',
          'table_name' => 'civicrm_volunteer_timetable',
          'entity' => 'VolunteerTimetable',
          'bao' => 'CRM_Yhvrequestform_DAO_VolunteerTimetable',
          'localizable' => 0,
        ],
        'number_of_volunteers' => [
          'name' => 'number_of_volunteers',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Yhvrequestform_ExtensionUtil::ts('Number Of Volunteers'),
          'description' => CRM_Yhvrequestform_ExtensionUtil::ts('Number of volunteers needed'),
          'where' => 'civicrm_volunteer_timetable.number_of_volunteers',
          'table_name' => 'civicrm_volunteer_timetable',
          'entity' => 'VolunteerTimetable',
          'bao' => 'CRM_Yhvrequestform_DAO_VolunteerTimetable',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'volunteer_timetable', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'volunteer_timetable', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
